stage: local
fetchInterval: 10000
processPastEvents: true
k8sEvents:
    namespaces: [] # no filter
    reasons:
        - Started
        - Killing
        - Failed
        - SystemOOM
    kinds:
        - Pod
        - Node
slack:
    enabled: true
    defaultChannel: C02J715D9MF
    events:
        - channel: C02MBM429C3
          namespaces:
              - 'salestrading'
              - 'businesspartner'
              - 'enmacc'
