stage: local
fetchInterval: 10000
processPastEvents: false
k8sEvents:
    namespaces:
        - 'traefik'
        - 'businesspartner'
        - 'pricefeed'
    reasons:
        - Started
        - Killing
        - Failed
        - SystemOOM
    kinds:
        - Pod
        - Node
slack:
    enabled: true
    defaultChannel: C02J715D9MF
    events:
        - namespace: traefik
          channel: C02J715D9MF
