stage: local
fetchInterval: 30000
k8sEvents:
    namespaces:
        - 'traefik'
slack:
    enabled: false
    defaultChannel: C02J715D9MF
    events:
        - namespace: traefik
          channel: C02J715D9MF
